server:
  port: 4444

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
          - Path=/auth/**
          - Path=/users/**
          filters:
          - RewritePath=/auth/(?<path>.*), /$\{path}
          - RewritePath=/users/(?<path>.*), /$\{path}
        - id: author-service
          uri: lb://author-service
          predicates:
          - Path=/authors/**
          filters:
          - RewritePath=/authors/(?<path>.*), /$\{path}
        - id: artstyle-service
          uri: lb://artstyle-service
          predicates:
          - Path=/artstyles/**
          filters:
          - RewritePath=/artstyles/(?<path>.*), /$\{path}
        - id: art-service
          uri: lb://art-service
          predicates:
          - Path=/art/**
          filters:
          - RewritePath=/art/(?<path>.*), /$\{path}